
FROM amazoncorretto:17-alpine-jdk

MAINTAINER melinda

COPY Users/Usuario/Downloads/portfolio.Web/portfolio.Web/target/portfolio.Web-0.0.1-SNAPSHOT.jar portfolio.Web-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","/portfolio.Web-0.0.1-SNAPSHOT.jar"]
